@baseUrl = http://localhost:5000 
@xAuthAccess = dXNlci1zdGlja3lfc2VjcmV0XzEyMzQ1Njc
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJibWNjb3JtaWNrIiwicm9sZXMiOlt7ImlkIjoxLCJuYW1lIjoiRmlsZSBNYW5hZ21lbnQiLCJwZXJtaXNzaW9ucyI6W3siaWQiOjEsIm5hbWUiOiJmaWxlLW1hbmFnZXIifV19XSwiaWF0IjoxNzcyNTg5NDY0LCJleHAiOjE3NzI1OTMwNjR9.cCdw7qWH2hRqp0oWCk7zQ4tg8yf7lK6mny1trNN4w1A

POST {{baseUrl}}/api/v1/users/sign-in/by-username
Content-Type: application/json 
Accept: application/json 
X-Auth-Trigger: {{xAuthAccess}}

{
"username": "bmccormick", "password": "123", "system_id": 2
}
##########

POST {{baseUrl}}/api/v1/users/sign-in/by-username 
Content-Type: application/json 
Accept: application/json 

{
"username": "bmccormickx", "password": "123asdf", "system_id": 1
}

##########

GET {{baseUrl}}/api/v1/token/translate
Accept: application/json
Authorization: Bearer {{jwt}}

##########

GET {{baseUrl}}/api/v1/users/search-id-by-email?email=amandabaker@example.org
Content-Type: application/json 
Accept: application/json 
Authorization: Bearer {{jwt}}
