@baseUrl = http://localhost:5000 
@xAuthAccess = dXNlci1zdGlja3lfc2VjcmV0XzEyMzQ1Njc
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJibWNjb3JtaWNrIiwicm9sZXMiOlt7ImlkIjoxLCJuYW1lIjoicm9sIDEiLCJwZXJtaXNzaW9ucyI6W3siaWQiOjEsIm5hbWUiOiJwZXJtaXNvIDEuMSJ9LHsiaWQiOjIsIm5hbWUiOiJwZXJtaXNvcyAxLjIifSx7ImlkIjozLCJuYW1lIjoicGVybWlzbyAxLjMifV19LHsiaWQiOjIsIm5hbWUiOiJyb2wgMiIsInBlcm1pc3Npb25zIjpbeyJpZCI6NCwibmFtZSI6InBlcm1pc28gMi4xIn0seyJpZCI6NSwibmFtZSI6InBlcm1pc28gMi4yIn1dfV0sImlhdCI6MTc3MDI0NjUxNywiZXhwIjoxNzcwMjUwMTE3fQ.rS99XchC4O2C7qQJ59g7ifFC3vefk3oobOjF2Zf5ZaI

POST {{baseUrl}}/api/v1/users/sign-in/by-username
Content-Type: application/json 
Accept: application/json 
X-Auth-Trigger: {{xAuthAccess}}

{
"username": "bmccormick", "password": "awdQ9G5kBkxZ5r4g", "system_id": 1
}
##########

POST {{baseUrl}}/api/v1/users/sign-in/by-username 
Content-Type: application/json 
Accept: application/json 

{
"username": "bmccormickx", "password": "123", "system_id": 1
}

##########

GET {{baseUrl}}/api/v1/token/translate
Accept: application/json
Authorization: Bearer {{jwt}}